const data = {
    products :[
        {
            _id:'1',
            name: 'Mezcal',
            category: 'Mezcal & Tequilas',
            image: '/images/product01.jpg',
            price:55000,
            countInStock: 10,
            brand:'El muerto',
            rating:4.5,
            numReviews:10,
            description:'Producto buenardo',
        },
        {
            _id:'2',
            name: 'Corona',
            category: 'Cervezas',
            image: '/images/product01.jpg',
            price:8000,
            countInStock: 5,
            brand:'Corona',
            rating:4.0,
            numReviews:15,
            description:'Producto aún más buenardo',
        },
        {
            _id:'3',
            name: 'Ron Medellin',
            category: 'Rones',
            image: '/images/product01.jpg',
            price:85000,
            countInStock: 0,
            brand:'Ron Medellín',
            rating:3.5,
            numReviews:8,
            description:'Medio buenardo',
        },
        {
            _id:'4',
            name: 'Mezcal',
            category: 'Mezcal & Tequilas',
            image: '/images/product01.jpg',
            price:55000,
            countInStock: 20,
            brand:'El muerto',
            rating:4.5,
            numReviews:10,
            description:'Producto buenardo',
        },
        {
            _id:'5',
            name: 'Mezcal',
            category: 'Mezcal & Tequilas',
            image: '/images/product01.jpg',
            price:55000,
            countInStock: 1,
            brand:'El muerto',
            rating:4.5,
            numReviews:10,
            description:'Producto buenardo',
        },
        {
            _id:'6',
            name: 'Mezcal',
            category: 'Mezcal & Tequilas',
            image: '/images/product01.jpg',
            price:55000,
            countInStock: 0,
            brand:'El muerto',
            rating:4.5,
            numReviews:10,
            description:'Producto buenardo',
        },
    ],
};

export default data;